### ISSUE TITLE
isXhr 为false的时候，即不上传服务器，图片怎么显示

### ISSUE THREAD

**Issue by fmisser** [Vanthink-UED/vue-core-image-upload#61]
我需要自己处理图片，此时组件不会显示选择的图片，如何操作

**Comment by JackPu** [comment]
你可以用imagechanged 函数获取文件内容，然后用 fileReader读取文件内容。

**Comment by yksmile007** [comment]
多文件的时候，为什么只能读取一个文件的信息？

**Comment by JackPu** [comment]
@yksmile007  最新的是返回一个数组给用户。

**Comment by zaguini** [comment]
I have a fix. To do this, you have to copy the component to your components folder instead of using node_modules (because you'll need to change the code, and when you run npm install you get the fresh code from npm).

Anyways, after copy the files go to src/vue-core-image-upload.vue, find the line 155 and after `upload(code)` insert the following line: `this.__dispatch('imagechanged',code)` and then the event will get fired. That is for croping the image.

If you want to resize, do the same thing on `doResize` function. Or whatever... You got the point, right? The `code` argument there is the processed image.

I hope it helps somebody who's facing the same issue. And with that you have full control over the styles, too.

[]'s

**Comment by yksmile007** [comment]
希望这个bug可以早点修复，卡在这里好久了，呜呜

**Comment by Kntt** [comment]
我是通过, changed事件拿到base64,来显示的, 自己处理上传, 上传成功用base64做显示用

**Comment by Grolia** [comment]
用imagechanged获取不到图片的src，求指教

**Comment by stanleyxu2005** [comment]
我也遇到这个问题，这里是最简单的示范

in template
```html
  <img :src="image"/>
  <VueCoreImageUpload
     @imagechanged="imagechanged"
     :isXhr="false"/>
```

in script
```javascript
export default {
  name: 'example',
  data: () => ({
    image: ''
  }),
  methods: {
      imagechanged(file) {
        const reader = new FileReader()
        reader.onload = (e) => {
          this.image = e.target.result
        }
        reader.readAsDataURL(file)
      },
  }
}
```
